<?php

namespace Zenva\WorkoutBundle\Repository;

/**
 * WorkoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkoutRepository extends \Doctrine\ORM\EntityRepository
{
}
